# Generated by Django 4.0.3 on 2022-03-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsets', '0008_remove_language_name_remove_profilemodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
