# Generated by Django 4.0.3 on 2022-03-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsets', '0009_profilemodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
